INSERT INTO USERS (USERNAME, PASSWORD, EMAIL) VALUES ('Masha', 'sa1', 'sa1@gmail.com');
INSERT INTO USERS (USERNAME, PASSWORD, EMAIL) VALUES ('Dasha', 'sa2', 'sa2@gmail.com');
INSERT INTO USERS (USERNAME, PASSWORD, EMAIL) VALUES ('Sasha', 'sa3', 'sa3@gmail.com');

